# Install Required Libraries

In [1]:
!pip install faker pandas numpy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: faker in c:\users\asus\appdata\roaming\python\python313\site-packages (40.28.1)
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy in c:\programdata\anaconda3\lib\site-packages (2.3.5)
Requirement already satisfied: tzdata in c:\programdata\anaconda3\lib\site-packages (from faker) (2025.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

# Import Libraries

In [2]:
import pandas as pd
import numpy as np
import random
import os

from faker import Faker

# Create Faker Object

In [3]:
fake = Faker()

# Create Folder Automatically

In [4]:
os.makedirs("data/raw", exist_ok=True)

# Generate Customers Dataset

In [5]:
customers = []

customer_types = ["REGULAR", "PREMIUM", "VIP"]

for i in range(1,501):

    email = fake.email()

    customers.append({

        "customer_id": i,

        "customer_name": fake.name(),

        "email": email,

        "registration_date": fake.date_between(start_date='-3y', end_date='today'),

        "customer_type": random.choice(customer_types)

    })

customers = pd.DataFrame(customers)

customers.head()

,customer_id,customer_name,email,registration_date,customer_type
0,1,Tammy Bryan,rodgersjonathan@example.com,2024-10-05,REGULAR
1,2,David Daniel,christine14@example.net,2024-08-06,REGULAR
2,3,Christopher Webb,ydalton@example.net,2025-04-10,PREMIUM
3,4,Cody Jimenez,allenjeffrey@example.net,2024-03-16,VIP
4,5,Rodney Moore,dawnwillis@example.net,2024-02-04,PREMIUM

# Introduce Invalid Emails (2%)

In [6]:
invalid_rows = customers.sample(frac=0.02).index

for i in invalid_rows:

    if random.choice([True, False]):

        customers.loc[i,"email"] = "abcgmail.com"

    else:

        customers.loc[i,"email"] = "xyz@yahoo"

customers.head()

,customer_id,customer_name,email,registration_date,customer_type
0,1,Tammy Bryan,rodgersjonathan@example.com,2024-10-05,REGULAR
1,2,David Daniel,christine14@example.net,2024-08-06,REGULAR
2,3,Christopher Webb,ydalton@example.net,2025-04-10,PREMIUM
3,4,Cody Jimenez,allenjeffrey@example.net,2024-03-16,VIP
4,5,Rodney Moore,dawnwillis@example.net,2024-02-04,PREMIUM

# Save Customers CSV

In [7]:
customers.to_csv("data/raw/customers.csv",index=False)

print("customers.csv saved successfully")

customers.csv saved successfully

# Generate Products Dataset

In [8]:
categories = {

    "Electronics":["Laptop","Mobile","Camera","Monitor","Keyboard"],

    "Clothing":["Shirt","Jeans","Jacket","Shoes","T-Shirt"],

    "Home":["Chair","Table","Sofa","Lamp","Fan"],

    "Books":["Python","SQL","Java","Spark","AI"]

}

products = []

for i in range(1,501):

    category = random.choice(list(categories.keys()))

    product = random.choice(categories[category])

    products.append({

        "product_id": i,

        "product_name": product,

        "category": category,

        "subcategory": product,

        "cost_price": round(random.uniform(100,10000),2)

    })

products = pd.DataFrame(products)

products.head()

   product_id product_name     category subcategory  cost_price
0           1         Sofa         Home        Sofa     2727.77
1           2      Monitor  Electronics     Monitor     3061.23
2           3        Table         Home       Table     3690.30
3           4      Monitor  Electronics     Monitor      257.30
4           5         Sofa         Home        Sofa      552.80

# Introduce Product Name Errors

In [9]:
random_rows = products.sample(frac=0.10).index

for i in random_rows:

    name = products.loc[i,"product_name"]

    style = random.randint(1,4)

    if style==1:

        products.loc[i,"product_name"] = " "+name+" "

    elif style==2:

        products.loc[i,"product_name"] = name.upper()

    elif style==3:

        products.loc[i,"product_name"] = name.lower()

    else:

        products.loc[i,"product_name"] = "  "+name.upper()

products.head()

   product_id product_name     category subcategory  cost_price
0           1         Sofa         Home        Sofa     2727.77
1           2      Monitor  Electronics     Monitor     3061.23
2           3        Table         Home       Table     3690.30
3           4      Monitor  Electronics     Monitor      257.30
4           5         Sofa         Home        Sofa      552.80

# Save Products CSV

In [10]:
products.to_csv("data/raw/products.csv",index=False)

print("products.csv saved successfully")

products.csv saved successfully

# Generate Orders Dataset

In [11]:
statuses = [

    "PLACED",

    "SHIPPED",

    "DELIVERED",

    "CANCELLED",

    "RETURNED"

]

regions = [

    "North",

    "South",

    "East",

    "West"

]

orders = []

for i in range(1,1001):

    orders.append({

        "order_id": i,

        "customer_id": random.randint(1,500),

        "order_date": fake.date_time_between(start_date='-2y',end_date='now'),

        "status": random.choice(statuses),

        "region_code": random.choice(regions)

    })

orders = pd.DataFrame(orders)

orders.head()

   order_id  customer_id          order_date     status region_code
0         1          196 2026-03-23 23:18:50     PLACED        East
1         2          258 2025-06-16 20:03:28   RETURNED        East
2         3          395 2024-09-14 05:29:58    SHIPPED       North
3         4           34 2025-10-16 21:45:22  CANCELLED        West
4         5          408 2025-01-08 04:33:07  DELIVERED       North

# Add NULL Customer IDs (5%)

In [12]:
null_rows = orders.sample(frac=0.05).index

orders.loc[null_rows,"customer_id"] = np.nan

# Wrong Date Format

In [13]:
wrong_dates = orders.sample(frac=0.05).index

for i in wrong_dates:

    orders.loc[i,"order_date"] = pd.to_datetime(
        orders.loc[i,"order_date"]
    ).strftime("%d-%m-%Y")

# Save Orders CSV

In [14]:
orders.to_csv("data/raw/orders.csv",index=False)

print("orders.csv saved successfully")

orders.csv saved successfully

# Generate Order Items

In [15]:
order_items = []

for i in range(1,3001):

    order_items.append({

        "item_id": i,

        "order_id": random.randint(1,1000),

        "product_id": random.randint(1,500),

        "quantity": random.randint(1,5),

        "unit_price": round(random.uniform(200,15000),2),

        "discount_percent": random.randint(0,50)

    })

order_items = pd.DataFrame(order_items)

order_items.head()

   item_id  order_id  product_id  quantity  unit_price  discount_percent
0        1       242         335         4     9703.00                14
1        2       257         461         1    11476.60                 6
2        3       290         389         3     4233.26                 8
3        4        97         298         5     6591.14                45
4        5       940         190         1    11618.90                41

# Add Negative Quantities

In [16]:
negative_rows = order_items.sample(frac=0.03).index

order_items.loc[negative_rows,"quantity"] *= -1

# Add Invalid Order IDs

In [17]:
invalid_rows = order_items.sample(2).index

order_items.loc[invalid_rows,"order_id"] = [2001,2002]

# Save Order Items CSV

In [18]:
order_items.to_csv("data/raw/order_items.csv",index=False)

print("order_items.csv saved successfully")

order_items.csv saved successfully

# Verify Everything

In [19]:
print(customers.head())

print(products.head())

print(orders.head())

print(order_items.head())

   customer_id     customer_name                        email  \
0            1       Tammy Bryan  rodgersjonathan@example.com
1            2      David Daniel      christine14@example.net
2            3  Christopher Webb          ydalton@example.net
3            4      Cody Jimenez     allenjeffrey@example.net
4            5      Rodney Moore       dawnwillis@example.net

  registration_date customer_type
0        2024-10-05       REGULAR
1        2024-08-06       REGULAR
2        2025-04-10       PREMIUM
3        2024-03-16           VIP
4        2024-02-04       PREMIUM
   product_id product_name     category subcategory  cost_price
0           1         Sofa         Home        Sofa     2727.77
1           2      Monitor  Electronics     Monitor     3061.23
2           3        Table         Home       Table     3690.30
3           4      Monitor  Electronics     Monitor      257.30
4           5         Sofa         Home        Sofa      552.80
   order_id  customer_id          order_date     status region_code
0         1        196.0 2026-03-23 23:18:50     PLACED        East
1         2        258.0 2025-06-16 20:03:28   RETURNED        East
2         3        395.0 2024-09-14 05:29:58    SHIPPED       North
3         4         34.0 2025-10-16 21:45:22  CANCELLED        West
4         5          NaN 2025-01-08 04:33:07  DELIVERED       North
   item_id  order_id  product_id  quantity  unit_price  discount_percent
0        1       242         335         4     9703.00                14
1        2       257         461         1    11476.60                 6
2        3       290         389         3     4233.26                 8
3        4        97         298         5     6591.14                45
4        5       940         190         1    11618.90                41

# Check Files

In [20]:
import os

print(os.listdir("data/raw"))

['.ipynb_checkpoints', 'customers.csv', 'orders.csv', 'order_items.csv', 'products.csv']